// <auto-generated />
using API_Health.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API_Health.Migrations
{
    [DbContext(typeof(APIDbContext))]
    [Migration("20230322091037_ShoppingCart")]
    partial class ShoppingCart
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("API_Health.Models.Client", b =>
                {
                    b.Property<int>("ID_client")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_client"));

                    b.Property<string>("Имя")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Логин")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Отчество")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Пароль")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Фамилия")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID_client");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("API_Health.Models.Provider", b =>
                {
                    b.Property<int>("ID_provider")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_provider"));

                    b.Property<string>("Имя")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Логин")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Отчество")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Пароль")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Склад")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Фамилия")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID_provider");

                    b.ToTable("Providers");
                });

            modelBuilder.Entity("API_Health.Models.ShoppingCart", b =>
                {
                    b.Property<int>("ID_cart")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_cart"));

                    b.Property<string>("Количество")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Название")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Цена")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID_cart");

                    b.ToTable("ShoppingCarts");
                });

            modelBuilder.Entity("API_Health.Models.ShoppingCartEmployee", b =>
                {
                    b.Property<int>("ID_cart")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_cart"));

                    b.Property<string>("Количество")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Название")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Цена")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID_cart");

                    b.ToTable("ShoppingCartEmployee");
                });
#pragma warning restore 612, 618
        }
    }
}
