// <auto-generated />
using API_Health.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API_Health.Migrations
{
    [DbContext(typeof(APIDbContext))]
    partial class APIDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("API_Health.Models.Client", b =>
                {
                    b.Property<int>("ID_client")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_client"));

                    b.Property<string>("Имя")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Логин")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Отчество")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Пароль")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Фамилия")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID_client");

                    b.ToTable("Clients");
                });
#pragma warning restore 612, 618
        }
    }
}
